START TRANSACTION;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- DataProtectionKeys

CREATE TABLE "DataProtectionKeys" (
    "Id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "FriendlyName" TEXT NULL,
    "Xml" TEXT NULL,

    CONSTRAINT "PK_DataProtectionKeys" PRIMARY KEY ("Id")
);

-- Identity

CREATE TABLE "AspNetRoles" (
  "Id" UUID NOT NULL,
  "Name" VARCHAR(256) NULL,
  "NormalizedName" VARCHAR(256) NULL,
  "ConcurrencyStamp" TEXT NULL,

  CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
  "Id" UUID NOT NULL,
  "UserName" VARCHAR(256) NULL,
  "NormalizedUserName" VARCHAR(256) NULL,
  "Email" VARCHAR(256) NULL,
  "NormalizedEmail" VARCHAR(256) NULL,
  "EmailConfirmed" BOOLEAN NOT NULL,
  "PasswordHash" TEXT NULL,
  "SecurityStamp" TEXT NULL,
  "ConcurrencyStamp" TEXT NULL,
  "PhoneNumber" TEXT NULL,
  "PhoneNumberConfirmed" BOOLEAN NOT NULL,
  "TwoFactorEnabled" BOOLEAN NOT NULL,
  "LockoutEnd" TIMESTAMP WITHOUT TIME ZONE NULL,
  "LockoutEnabled" BOOLEAN NOT NULL,
  "AccessFailedCount" INTEGER NOT NULL,

  CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
  "Id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "RoleId" UUID NOT NULL,
  "ClaimType" TEXT NULL,
  "ClaimValue" TEXT NULL,

  CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
  CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
  "Id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "UserId" UUID NOT NULL,
  "ClaimType" TEXT NULL,
  "ClaimValue" TEXT NULL,

  CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
  CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
  "LoginProvider" TEXT NOT NULL,
  "ProviderKey" TEXT NOT NULL,
  "ProviderDisplayName" TEXT NULL,
  "UserId" UUID NOT NULL,

  CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
  CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
  "UserId" UUID NOT NULL,
  "RoleId" UUID NOT NULL,

  CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
  CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
  CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
  "UserId" UUID NOT NULL,
  "LoginProvider" TEXT NOT NULL,
  "Name" TEXT NOT NULL,
  "Value" TEXT NULL,

  CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
  CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

COMMIT;
